# ref: https://superfile.dev/configure/superfile-config/#default-superfile-config

debug = false
ignore_missing_fields = false
auto_check_update = true
cd_on_quit = false
shell_close_on_success = false

# use default $EDITOR
editor = ""
dir_editor = ""

# open in current directory
default_directory = "."

show_panel_footer_info = false
file_size_use_si = false
default_sort_type = 0
case_sensitive_sort = false
sort_order_reversed = false

file_panel_extra_columns = 0
file_panel_name_percent = 50

page_scroll_size = 0

theme = "adwaita-dark"
transparent_background = false
code_previewer = ""
nerdfont = true
show_select_icons = true
default_open_file_preview = true

show_image_preview = true
file_preview_width = 0
enable_file_preview_border = false

sidebar_width = 20

border_top = '─'
border_bottom = '─'
border_left = '│'
border_right = '│'
border_top_left = '╭'
border_top_right = '╮'
border_bottom_left = '╰'
border_bottom_right = '╯'
border_middle_left = '├'
border_middle_right = '┤'

# plugins
# ref: https://superfile.dev/list/plugin-list/.
metadata = false
enable_md5_checksum = false
zoxide_support = true

[open_with]
