# HACK: fix to thin out bold fonts so that they render properly
text_composition_strategy legacy

font_family JetBrains Mono
font_size 11
cursor_blink_interval 0
url_style straight
enable_audio_bell no
hide_window_decorations yes
tab_bar_style powerline
